/* game1.vala.c generated by valac 0.22.1, the Vala compiler
 * generated from game1.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <SDL2/SDL_events.h>
#include <chipmunk/chipmunk.h>
#include <SDL2/SDL_rect.h>
#include <float.h>
#include <math.h>


#define AVAL_TYPE_SCREEN_STATE (aval_screen_state_get_type ())
#define AVAL_SCREEN_STATE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AVAL_TYPE_SCREEN_STATE, AvalScreenState))
#define AVAL_IS_SCREEN_STATE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AVAL_TYPE_SCREEN_STATE))
#define AVAL_SCREEN_STATE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), AVAL_TYPE_SCREEN_STATE, AvalScreenStateIface))

typedef struct _AvalScreenState AvalScreenState;
typedef struct _AvalScreenStateIface AvalScreenStateIface;

#define PLATFORM_TYPE_GAME1 (platform_game1_get_type ())
#define PLATFORM_GAME1(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PLATFORM_TYPE_GAME1, PlatformGame1))
#define PLATFORM_GAME1_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PLATFORM_TYPE_GAME1, PlatformGame1Class))
#define PLATFORM_IS_GAME1(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PLATFORM_TYPE_GAME1))
#define PLATFORM_IS_GAME1_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PLATFORM_TYPE_GAME1))
#define PLATFORM_GAME1_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PLATFORM_TYPE_GAME1, PlatformGame1Class))

typedef struct _PlatformGame1 PlatformGame1;
typedef struct _PlatformGame1Class PlatformGame1Class;
typedef struct _PlatformGame1Private PlatformGame1Private;

#define PLATFORM_TYPE_PLAYER (platform_player_get_type ())
#define PLATFORM_PLAYER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PLATFORM_TYPE_PLAYER, PlatformPlayer))
#define PLATFORM_PLAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PLATFORM_TYPE_PLAYER, PlatformPlayerClass))
#define PLATFORM_IS_PLAYER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PLATFORM_TYPE_PLAYER))
#define PLATFORM_IS_PLAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PLATFORM_TYPE_PLAYER))
#define PLATFORM_PLAYER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PLATFORM_TYPE_PLAYER, PlatformPlayerClass))

typedef struct _PlatformPlayer PlatformPlayer;
typedef struct _PlatformPlayerClass PlatformPlayerClass;

#define PLATFORM_TYPE_LEVEL (platform_level_get_type ())
#define PLATFORM_LEVEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PLATFORM_TYPE_LEVEL, PlatformLevel))
#define PLATFORM_LEVEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PLATFORM_TYPE_LEVEL, PlatformLevelClass))
#define PLATFORM_IS_LEVEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PLATFORM_TYPE_LEVEL))
#define PLATFORM_IS_LEVEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PLATFORM_TYPE_LEVEL))
#define PLATFORM_LEVEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PLATFORM_TYPE_LEVEL, PlatformLevelClass))

typedef struct _PlatformLevel PlatformLevel;
typedef struct _PlatformLevelClass PlatformLevelClass;
#define _cpSpaceFree0(var) ((var == NULL) ? NULL : (var = (cpSpaceFree (var), NULL)))
#define _platform_player_unref0(var) ((var == NULL) ? NULL : (var = (platform_player_unref (var), NULL)))
#define _platform_level_unref0(var) ((var == NULL) ? NULL : (var = (platform_level_unref (var), NULL)))

struct _AvalScreenStateIface {
	GTypeInterface parent_iface;
	void (*on_enter) (AvalScreenState* self);
	void (*on_event) (AvalScreenState* self, SDL_Event e);
	void (*on_update) (AvalScreenState* self);
	void (*draw) (AvalScreenState* self);
	void (*on_leave) (AvalScreenState* self);
};

struct _PlatformGame1 {
	GObject parent_instance;
	PlatformGame1Private * priv;
};

struct _PlatformGame1Class {
	GObjectClass parent_class;
};

struct _PlatformGame1Private {
	cpSpace* space;
	SDL_Rect view;
	PlatformPlayer* player;
	PlatformLevel* level;
};


static gpointer platform_game1_parent_class = NULL;
static AvalScreenStateIface* platform_game1_aval_screen_state_parent_iface = NULL;

GType aval_screen_state_get_type (void) G_GNUC_CONST;
GType platform_game1_get_type (void) G_GNUC_CONST;
gpointer platform_player_ref (gpointer instance);
void platform_player_unref (gpointer instance);
GParamSpec* platform_param_spec_player (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void platform_value_set_player (GValue* value, gpointer v_object);
void platform_value_take_player (GValue* value, gpointer v_object);
gpointer platform_value_get_player (const GValue* value);
GType platform_player_get_type (void) G_GNUC_CONST;
gpointer platform_level_ref (gpointer instance);
void platform_level_unref (gpointer instance);
GParamSpec* platform_param_spec_level (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void platform_value_set_level (GValue* value, gpointer v_object);
void platform_value_take_level (GValue* value, gpointer v_object);
gpointer platform_value_get_level (const GValue* value);
GType platform_level_get_type (void) G_GNUC_CONST;
#define PLATFORM_GAME1_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), PLATFORM_TYPE_GAME1, PlatformGame1Private))
enum  {
	PLATFORM_GAME1_DUMMY_PROPERTY
};
#define PLATFORM_GAME1_TIME_STEP (1.0 / 60.0)
static void platform_game1_real_on_enter (AvalScreenState* base);
PlatformLevel* platform_level_new (cpSpace* space, SDL_Rect view);
PlatformLevel* platform_level_construct (GType object_type, cpSpace* space, SDL_Rect view);
PlatformPlayer* platform_player_new (SDL_Point start_position, cpSpace* space, SDL_Rect view);
PlatformPlayer* platform_player_construct (GType object_type, SDL_Point start_position, cpSpace* space, SDL_Rect view);
static void platform_game1_real_on_event (AvalScreenState* base, SDL_Event e);
void platform_level_on_event (PlatformLevel* self, SDL_Event e);
void platform_player_on_event (PlatformPlayer* self, SDL_Event e);
static void platform_game1_real_on_update (AvalScreenState* base);
void platform_level_update (PlatformLevel* self);
void platform_player_update (PlatformPlayer* self);
static void platform_game1_real_draw (AvalScreenState* base);
void platform_level_draw (PlatformLevel* self);
void platform_player_draw (PlatformPlayer* self);
static void platform_game1_real_on_leave (AvalScreenState* base);
void platform_player_physics_dispose (PlatformPlayer* self, cpSpace* space);
void platform_player_dispose (PlatformPlayer* self);
void platform_level_physics_dispose (PlatformLevel* self, cpSpace* space);
void platform_level_dispose (PlatformLevel* self);
PlatformGame1* platform_game1_new (void);
PlatformGame1* platform_game1_construct (GType object_type);
static void platform_game1_finalize (GObject* obj);

static const cpVect PLATFORM_GAME1_GRAVITY = {(gdouble) 0, (gdouble) 0.2f};

static void platform_game1_real_on_enter (AvalScreenState* base) {
	PlatformGame1 * self;
	cpSpace* _tmp0_ = NULL;
	cpSpace* _tmp1_ = NULL;
	SDL_Rect _tmp2_ = {0};
	cpSpace* _tmp3_ = NULL;
	SDL_Rect _tmp4_ = {0};
	PlatformLevel* _tmp5_ = NULL;
	SDL_Point _tmp6_ = {0};
	cpSpace* _tmp7_ = NULL;
	SDL_Rect _tmp8_ = {0};
	PlatformPlayer* _tmp9_ = NULL;
	self = (PlatformGame1*) base;
	_tmp0_ = cpSpaceNew ();
	_cpSpaceFree0 (self->priv->space);
	self->priv->space = _tmp0_;
	_tmp1_ = self->priv->space;
	_tmp1_->gravity = PLATFORM_GAME1_GRAVITY;
	_tmp2_.x = 0;
	_tmp2_.y = 0;
	_tmp2_.w = 960;
	_tmp2_.h = 544;
	self->priv->view = _tmp2_;
	_tmp3_ = self->priv->space;
	_tmp4_ = self->priv->view;
	_tmp5_ = platform_level_new (_tmp3_, _tmp4_);
	_platform_level_unref0 (self->priv->level);
	self->priv->level = _tmp5_;
	_tmp6_.x = 120;
	_tmp6_.y = 0;
	_tmp7_ = self->priv->space;
	_tmp8_ = self->priv->view;
	_tmp9_ = platform_player_new (_tmp6_, _tmp7_, _tmp8_);
	_platform_player_unref0 (self->priv->player);
	self->priv->player = _tmp9_;
}


static void platform_game1_real_on_event (AvalScreenState* base, SDL_Event e) {
	PlatformGame1 * self;
	PlatformLevel* _tmp0_ = NULL;
	SDL_Event _tmp1_ = {0};
	PlatformPlayer* _tmp2_ = NULL;
	SDL_Event _tmp3_ = {0};
	self = (PlatformGame1*) base;
	_tmp0_ = self->priv->level;
	_tmp1_ = e;
	platform_level_on_event (_tmp0_, _tmp1_);
	_tmp2_ = self->priv->player;
	_tmp3_ = e;
	platform_player_on_event (_tmp2_, _tmp3_);
}


static void platform_game1_real_on_update (AvalScreenState* base) {
	PlatformGame1 * self;
	PlatformLevel* _tmp0_ = NULL;
	PlatformPlayer* _tmp1_ = NULL;
	self = (PlatformGame1*) base;
	_tmp0_ = self->priv->level;
	platform_level_update (_tmp0_);
	_tmp1_ = self->priv->player;
	platform_player_update (_tmp1_);
	{
		gdouble time = 0.0;
		time = (gdouble) 0;
		{
			gboolean _tmp2_ = FALSE;
			_tmp2_ = TRUE;
			while (TRUE) {
				gboolean _tmp3_ = FALSE;
				gdouble _tmp5_ = 0.0;
				cpSpace* _tmp6_ = NULL;
				_tmp3_ = _tmp2_;
				if (!_tmp3_) {
					gdouble _tmp4_ = 0.0;
					_tmp4_ = time;
					time = _tmp4_ + PLATFORM_GAME1_TIME_STEP;
				}
				_tmp2_ = FALSE;
				_tmp5_ = time;
				if (!(_tmp5_ < ((gdouble) 2))) {
					break;
				}
				_tmp6_ = self->priv->space;
				cpSpaceStep (_tmp6_, PLATFORM_GAME1_TIME_STEP);
			}
		}
	}
}


static void platform_game1_real_draw (AvalScreenState* base) {
	PlatformGame1 * self;
	PlatformLevel* _tmp0_ = NULL;
	PlatformPlayer* _tmp1_ = NULL;
	self = (PlatformGame1*) base;
	_tmp0_ = self->priv->level;
	platform_level_draw (_tmp0_);
	_tmp1_ = self->priv->player;
	platform_player_draw (_tmp1_);
}


static void platform_game1_real_on_leave (AvalScreenState* base) {
	PlatformGame1 * self;
	PlatformPlayer* _tmp0_ = NULL;
	cpSpace* _tmp1_ = NULL;
	PlatformPlayer* _tmp2_ = NULL;
	PlatformLevel* _tmp3_ = NULL;
	cpSpace* _tmp4_ = NULL;
	PlatformLevel* _tmp5_ = NULL;
	self = (PlatformGame1*) base;
	_tmp0_ = self->priv->player;
	_tmp1_ = self->priv->space;
	platform_player_physics_dispose (_tmp0_, _tmp1_);
	_tmp2_ = self->priv->player;
	platform_player_dispose (_tmp2_);
	_platform_player_unref0 (self->priv->player);
	self->priv->player = NULL;
	_tmp3_ = self->priv->level;
	_tmp4_ = self->priv->space;
	platform_level_physics_dispose (_tmp3_, _tmp4_);
	_tmp5_ = self->priv->level;
	platform_level_dispose (_tmp5_);
	_platform_level_unref0 (self->priv->level);
	self->priv->level = NULL;
}


PlatformGame1* platform_game1_construct (GType object_type) {
	PlatformGame1 * self = NULL;
	self = (PlatformGame1*) g_object_new (object_type, NULL);
	return self;
}


PlatformGame1* platform_game1_new (void) {
	return platform_game1_construct (PLATFORM_TYPE_GAME1);
}


static void platform_game1_class_init (PlatformGame1Class * klass) {
	platform_game1_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (PlatformGame1Private));
	G_OBJECT_CLASS (klass)->finalize = platform_game1_finalize;
}


static void platform_game1_aval_screen_state_interface_init (AvalScreenStateIface * iface) {
	platform_game1_aval_screen_state_parent_iface = g_type_interface_peek_parent (iface);
	iface->on_enter = (void (*)(AvalScreenState*)) platform_game1_real_on_enter;
	iface->on_event = (void (*)(AvalScreenState*, SDL_Event)) platform_game1_real_on_event;
	iface->on_update = (void (*)(AvalScreenState*)) platform_game1_real_on_update;
	iface->draw = (void (*)(AvalScreenState*)) platform_game1_real_draw;
	iface->on_leave = (void (*)(AvalScreenState*)) platform_game1_real_on_leave;
}


static void platform_game1_instance_init (PlatformGame1 * self) {
	self->priv = PLATFORM_GAME1_GET_PRIVATE (self);
}


static void platform_game1_finalize (GObject* obj) {
	PlatformGame1 * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PLATFORM_TYPE_GAME1, PlatformGame1);
	_cpSpaceFree0 (self->priv->space);
	_platform_player_unref0 (self->priv->player);
	_platform_level_unref0 (self->priv->level);
	G_OBJECT_CLASS (platform_game1_parent_class)->finalize (obj);
}


GType platform_game1_get_type (void) {
	static volatile gsize platform_game1_type_id__volatile = 0;
	if (g_once_init_enter (&platform_game1_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PlatformGame1Class), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) platform_game1_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PlatformGame1), 0, (GInstanceInitFunc) platform_game1_instance_init, NULL };
		static const GInterfaceInfo aval_screen_state_info = { (GInterfaceInitFunc) platform_game1_aval_screen_state_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType platform_game1_type_id;
		platform_game1_type_id = g_type_register_static (G_TYPE_OBJECT, "PlatformGame1", &g_define_type_info, 0);
		g_type_add_interface_static (platform_game1_type_id, AVAL_TYPE_SCREEN_STATE, &aval_screen_state_info);
		g_once_init_leave (&platform_game1_type_id__volatile, platform_game1_type_id);
	}
	return platform_game1_type_id__volatile;
}



