/* level.vala.c generated by valac 0.22.1, the Vala compiler
 * generated from level.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <chipmunk/chipmunk.h>
#include <SDL2/SDL_render.h>
#include <SDL2/SDL_rect.h>
#include <SDL2/SDL_image.h>
#include <float.h>
#include <math.h>
#include <SDL2/SDL_events.h>
#include <gobject/gvaluecollector.h>


#define PLATFORM_TYPE_LEVEL (platform_level_get_type ())
#define PLATFORM_LEVEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PLATFORM_TYPE_LEVEL, PlatformLevel))
#define PLATFORM_LEVEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PLATFORM_TYPE_LEVEL, PlatformLevelClass))
#define PLATFORM_IS_LEVEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PLATFORM_TYPE_LEVEL))
#define PLATFORM_IS_LEVEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PLATFORM_TYPE_LEVEL))
#define PLATFORM_LEVEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PLATFORM_TYPE_LEVEL, PlatformLevelClass))

typedef struct _PlatformLevel PlatformLevel;
typedef struct _PlatformLevelClass PlatformLevelClass;
typedef struct _PlatformLevelPrivate PlatformLevelPrivate;
#define _cpShapeFree0(var) ((var == NULL) ? NULL : (var = (cpShapeFree (var), NULL)))
#define _SDL_DestroyTexture0(var) ((var == NULL) ? NULL : (var = (SDL_DestroyTexture (var), NULL)))
typedef struct _PlatformParamSpecLevel PlatformParamSpecLevel;

struct _PlatformLevel {
	GTypeInstance parent_instance;
	volatile int ref_count;
	PlatformLevelPrivate * priv;
};

struct _PlatformLevelClass {
	GTypeClass parent_class;
	void (*finalize) (PlatformLevel *self);
};

struct _PlatformLevelPrivate {
	cpSegmentShape* ground;
	SDL_Texture* background;
	SDL_Rect view;
};

struct _PlatformParamSpecLevel {
	GParamSpec parent_instance;
};


static gpointer platform_level_parent_class = NULL;
extern SDL_Renderer* aval_game_WIN_RENDERER;
extern gint aval_game_WH;
extern gint aval_game_WW;

gpointer platform_level_ref (gpointer instance);
void platform_level_unref (gpointer instance);
GParamSpec* platform_param_spec_level (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void platform_value_set_level (GValue* value, gpointer v_object);
void platform_value_take_level (GValue* value, gpointer v_object);
gpointer platform_value_get_level (const GValue* value);
GType platform_level_get_type (void) G_GNUC_CONST;
#define PLATFORM_LEVEL_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), PLATFORM_TYPE_LEVEL, PlatformLevelPrivate))
enum  {
	PLATFORM_LEVEL_DUMMY_PROPERTY
};
PlatformLevel* platform_level_new (cpSpace* space, SDL_Rect view);
PlatformLevel* platform_level_construct (GType object_type, cpSpace* space, SDL_Rect view);
void platform_level_on_event (PlatformLevel* self, SDL_Event e);
void platform_level_update (PlatformLevel* self);
void platform_level_draw (PlatformLevel* self);
void platform_level_dispose (PlatformLevel* self);
void platform_level_physics_dispose (PlatformLevel* self, cpSpace* space);
static void platform_level_finalize (PlatformLevel* obj);


PlatformLevel* platform_level_construct (GType object_type, cpSpace* space, SDL_Rect view) {
	PlatformLevel* self = NULL;
	SDL_Rect _tmp0_ = {0};
	SDL_Renderer* _tmp1_ = NULL;
	SDL_Texture* _tmp2_ = NULL;
	cpSpace* _tmp3_ = NULL;
	cpBody* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	cpVect _tmp6_ = {0};
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	cpVect _tmp9_ = {0};
	cpSegmentShape* _tmp10_ = NULL;
	cpSegmentShape* _tmp11_ = NULL;
	cpSegmentShape* _tmp12_ = NULL;
	cpSpace* _tmp13_ = NULL;
	cpSegmentShape* _tmp14_ = NULL;
	g_return_val_if_fail (space != NULL, NULL);
	self = (PlatformLevel*) g_type_create_instance (object_type);
	_tmp0_ = view;
	self->priv->view = _tmp0_;
	_tmp1_ = aval_game_WIN_RENDERER;
	_tmp2_ = IMG_LoadTexture (_tmp1_, "demo.png");
	_SDL_DestroyTexture0 (self->priv->background);
	self->priv->background = _tmp2_;
	_tmp3_ = space;
	_tmp4_ = _tmp3_->staticBody;
	_tmp5_ = aval_game_WH;
	_tmp6_.x = (gdouble) (-100);
	_tmp6_.y = (gdouble) ((_tmp5_ * 0.86f) - 32);
	_tmp7_ = aval_game_WW;
	_tmp8_ = aval_game_WH;
	_tmp9_.x = (gdouble) (_tmp7_ + 100);
	_tmp9_.y = (gdouble) ((_tmp8_ * 0.86f) - 32);
	_tmp10_ = cpSegmentShapeNew (_tmp4_, _tmp6_, _tmp9_, (gdouble) 1);
	_cpShapeFree0 (self->priv->ground);
	self->priv->ground = _tmp10_;
	_tmp11_ = self->priv->ground;
	((cpShape*) _tmp11_)->u = (gdouble) 1;
	_tmp12_ = self->priv->ground;
	((cpShape*) _tmp12_)->collision_type = (cpCollisionType) 0;
	_tmp13_ = space;
	_tmp14_ = self->priv->ground;
	cpSpaceAddShape (_tmp13_, (cpShape*) _tmp14_);
	return self;
}


PlatformLevel* platform_level_new (cpSpace* space, SDL_Rect view) {
	return platform_level_construct (PLATFORM_TYPE_LEVEL, space, view);
}


void platform_level_on_event (PlatformLevel* self, SDL_Event e) {
	g_return_if_fail (self != NULL);
}


void platform_level_update (PlatformLevel* self) {
	g_return_if_fail (self != NULL);
}


void platform_level_draw (PlatformLevel* self) {
	SDL_Renderer* _tmp0_ = NULL;
	SDL_Texture* _tmp1_ = NULL;
	SDL_Rect _tmp2_ = {0};
	SDL_Rect _tmp3_ = {0};
	gint _tmp4_ = 0;
	SDL_Rect _tmp5_ = {0};
	gint _tmp6_ = 0;
	SDL_Rect _tmp7_ = {0};
	g_return_if_fail (self != NULL);
	_tmp0_ = aval_game_WIN_RENDERER;
	_tmp1_ = self->priv->background;
	_tmp2_ = self->priv->view;
	_tmp3_ = self->priv->view;
	_tmp4_ = _tmp3_.w;
	_tmp5_ = self->priv->view;
	_tmp6_ = _tmp5_.h;
	_tmp7_.x = 0;
	_tmp7_.y = 0;
	_tmp7_.w = _tmp4_;
	_tmp7_.h = _tmp6_;
	SDL_RenderCopy (_tmp0_, _tmp1_, &_tmp2_, &_tmp7_);
}


void platform_level_dispose (PlatformLevel* self) {
	g_return_if_fail (self != NULL);
	_SDL_DestroyTexture0 (self->priv->background);
	self->priv->background = NULL;
}


void platform_level_physics_dispose (PlatformLevel* self, cpSpace* space) {
	cpSpace* _tmp0_ = NULL;
	cpSegmentShape* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (space != NULL);
	_tmp0_ = space;
	_tmp1_ = self->priv->ground;
	cpSpaceRemoveShape (_tmp0_, (cpShape*) _tmp1_);
}


static void platform_value_level_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void platform_value_level_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		platform_level_unref (value->data[0].v_pointer);
	}
}


static void platform_value_level_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = platform_level_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer platform_value_level_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* platform_value_level_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		PlatformLevel* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = platform_level_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* platform_value_level_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	PlatformLevel** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = platform_level_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* platform_param_spec_level (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	PlatformParamSpecLevel* spec;
	g_return_val_if_fail (g_type_is_a (object_type, PLATFORM_TYPE_LEVEL), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer platform_value_get_level (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, PLATFORM_TYPE_LEVEL), NULL);
	return value->data[0].v_pointer;
}


void platform_value_set_level (GValue* value, gpointer v_object) {
	PlatformLevel* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, PLATFORM_TYPE_LEVEL));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, PLATFORM_TYPE_LEVEL));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		platform_level_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		platform_level_unref (old);
	}
}


void platform_value_take_level (GValue* value, gpointer v_object) {
	PlatformLevel* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, PLATFORM_TYPE_LEVEL));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, PLATFORM_TYPE_LEVEL));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		platform_level_unref (old);
	}
}


static void platform_level_class_init (PlatformLevelClass * klass) {
	platform_level_parent_class = g_type_class_peek_parent (klass);
	PLATFORM_LEVEL_CLASS (klass)->finalize = platform_level_finalize;
	g_type_class_add_private (klass, sizeof (PlatformLevelPrivate));
}


static void platform_level_instance_init (PlatformLevel * self) {
	self->priv = PLATFORM_LEVEL_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void platform_level_finalize (PlatformLevel* obj) {
	PlatformLevel * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PLATFORM_TYPE_LEVEL, PlatformLevel);
	_cpShapeFree0 (self->priv->ground);
	_SDL_DestroyTexture0 (self->priv->background);
}


GType platform_level_get_type (void) {
	static volatile gsize platform_level_type_id__volatile = 0;
	if (g_once_init_enter (&platform_level_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { platform_value_level_init, platform_value_level_free_value, platform_value_level_copy_value, platform_value_level_peek_pointer, "p", platform_value_level_collect_value, "p", platform_value_level_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (PlatformLevelClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) platform_level_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PlatformLevel), 0, (GInstanceInitFunc) platform_level_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType platform_level_type_id;
		platform_level_type_id = g_type_register_fundamental (g_type_fundamental_next (), "PlatformLevel", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&platform_level_type_id__volatile, platform_level_type_id);
	}
	return platform_level_type_id__volatile;
}


gpointer platform_level_ref (gpointer instance) {
	PlatformLevel* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void platform_level_unref (gpointer instance) {
	PlatformLevel* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		PLATFORM_LEVEL_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



