/* main.vala.c generated by valac 0.22.1, the Vala compiler
 * generated from main.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <SDL2/SDL.h>
#include <SDL2/SDL_image.h>
#include <SDL2/SDL_mixer.h>
#include <SDL2/SDL_video.h>
#include <SDL2/SDL_render.h>
#include <SDL2/SDL_events.h>


#define AVAL_TYPE_GAME (aval_game_get_type ())
#define AVAL_GAME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AVAL_TYPE_GAME, AvalGame))
#define AVAL_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AVAL_TYPE_GAME, AvalGameClass))
#define AVAL_IS_GAME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AVAL_TYPE_GAME))
#define AVAL_IS_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AVAL_TYPE_GAME))
#define AVAL_GAME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AVAL_TYPE_GAME, AvalGameClass))

typedef struct _AvalGame AvalGame;
typedef struct _AvalGameClass AvalGameClass;
typedef struct _AvalGamePrivate AvalGamePrivate;

#define PLATFORM_TYPE_MAIN (platform_main_get_type ())
#define PLATFORM_MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PLATFORM_TYPE_MAIN, PlatformMain))
#define PLATFORM_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PLATFORM_TYPE_MAIN, PlatformMainClass))
#define PLATFORM_IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PLATFORM_TYPE_MAIN))
#define PLATFORM_IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PLATFORM_TYPE_MAIN))
#define PLATFORM_MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PLATFORM_TYPE_MAIN, PlatformMainClass))

typedef struct _PlatformMain PlatformMain;
typedef struct _PlatformMainClass PlatformMainClass;
typedef struct _PlatformMainPrivate PlatformMainPrivate;
#define _g_rand_free0(var) ((var == NULL) ? NULL : (var = (g_rand_free (var), NULL)))
#define _SDL_free0(var) ((var == NULL) ? NULL : (var = (SDL_free (var), NULL)))

#define AVAL_TYPE_SCREEN_STATE (aval_screen_state_get_type ())
#define AVAL_SCREEN_STATE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AVAL_TYPE_SCREEN_STATE, AvalScreenState))
#define AVAL_IS_SCREEN_STATE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AVAL_TYPE_SCREEN_STATE))
#define AVAL_SCREEN_STATE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), AVAL_TYPE_SCREEN_STATE, AvalScreenStateIface))

typedef struct _AvalScreenState AvalScreenState;
typedef struct _AvalScreenStateIface AvalScreenStateIface;

#define PLATFORM_TYPE_GAME1 (platform_game1_get_type ())
#define PLATFORM_GAME1(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PLATFORM_TYPE_GAME1, PlatformGame1))
#define PLATFORM_GAME1_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PLATFORM_TYPE_GAME1, PlatformGame1Class))
#define PLATFORM_IS_GAME1(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PLATFORM_TYPE_GAME1))
#define PLATFORM_IS_GAME1_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PLATFORM_TYPE_GAME1))
#define PLATFORM_GAME1_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PLATFORM_TYPE_GAME1, PlatformGame1Class))

typedef struct _PlatformGame1 PlatformGame1;
typedef struct _PlatformGame1Class PlatformGame1Class;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _AvalGame {
	GTypeInstance parent_instance;
	volatile int ref_count;
	AvalGamePrivate * priv;
};

struct _AvalGameClass {
	GTypeClass parent_class;
	void (*finalize) (AvalGame *self);
};

struct _PlatformMain {
	AvalGame parent_instance;
	PlatformMainPrivate * priv;
};

struct _PlatformMainClass {
	AvalGameClass parent_class;
};

struct _AvalScreenStateIface {
	GTypeInterface parent_iface;
	void (*on_enter) (AvalScreenState* self);
	void (*on_event) (AvalScreenState* self, SDL_Event e);
	void (*on_update) (AvalScreenState* self);
	void (*draw) (AvalScreenState* self);
	void (*on_leave) (AvalScreenState* self);
};


static gpointer platform_main_parent_class = NULL;
extern GRand* platform_main_RANDOM;
GRand* platform_main_RANDOM = NULL;
extern SDL_Window* aval_game_WINDOW;
extern gint aval_game_WW;
extern gint aval_game_WH;
extern SDL_Renderer* aval_game_WIN_RENDERER;
extern AvalScreenState* aval_game_STATE;

gpointer aval_game_ref (gpointer instance);
void aval_game_unref (gpointer instance);
GParamSpec* aval_param_spec_game (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void aval_value_set_game (GValue* value, gpointer v_object);
void aval_value_take_game (GValue* value, gpointer v_object);
gpointer aval_value_get_game (const GValue* value);
GType aval_game_get_type (void) G_GNUC_CONST;
GType platform_main_get_type (void) G_GNUC_CONST;
enum  {
	PLATFORM_MAIN_DUMMY_PROPERTY
};
void platform_main_main (void);
void aval_game_init (int sdl_flags, IMG_InitFlags img_flags);
void aval_game_set_fps (gint nframe_rate);
GType aval_screen_state_get_type (void) G_GNUC_CONST;
void aval_game_change_state (AvalScreenState* nstate);
PlatformGame1* platform_game1_new (void);
PlatformGame1* platform_game1_construct (GType object_type);
GType platform_game1_get_type (void) G_GNUC_CONST;
void aval_screen_state_on_enter (AvalScreenState* self);
void aval_game_main_loop (void);
void aval_game_quit (void);
PlatformMain* platform_main_new (void);
PlatformMain* platform_main_construct (GType object_type);
AvalGame* aval_game_new (void);
AvalGame* aval_game_construct (GType object_type);
static void platform_main_finalize (AvalGame* obj);


void platform_main_main (void) {
	GRand* _tmp0_ = NULL;
	SDL_Window* _tmp1_ = NULL;
	SDL_Window* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	SDL_Window* _tmp5_ = NULL;
	SDL_Renderer* _tmp6_ = NULL;
	PlatformGame1* _tmp7_ = NULL;
	PlatformGame1* _tmp8_ = NULL;
	aval_game_init (SDL_INIT_EVERYTHING, IMG_INIT_PNG);
	Mix_OpenAudio (48000, (guint16) AUDIO_S16SYS, 2, 4096);
	_tmp0_ = g_rand_new ();
	_g_rand_free0 (platform_main_RANDOM);
	platform_main_RANDOM = _tmp0_;
	aval_game_set_fps (60);
	_tmp1_ = SDL_CreateWindow ("Platformer", (gint) SDL_WINDOWPOS_CENTERED_MASK, (gint) SDL_WINDOWPOS_CENTERED_MASK, 960, 544, (guint32) (SDL_WINDOW_SHOWN | SDL_WINDOW_RESIZABLE));
	_SDL_free0 (aval_game_WINDOW);
	aval_game_WINDOW = _tmp1_;
	_tmp2_ = aval_game_WINDOW;
	SDL_GetWindowSize (_tmp2_, &_tmp3_, &_tmp4_);
	aval_game_WW = _tmp3_;
	aval_game_WH = _tmp4_;
	_tmp5_ = aval_game_WINDOW;
	_tmp6_ = SDL_CreateRenderer (_tmp5_, -1, (guint32) SDL_RENDERER_ACCELERATED);
	_SDL_free0 (aval_game_WIN_RENDERER);
	aval_game_WIN_RENDERER = _tmp6_;
	_tmp7_ = platform_game1_new ();
	_tmp8_ = _tmp7_;
	aval_game_change_state ((AvalScreenState*) _tmp8_);
	_g_object_unref0 (_tmp8_);
	while (TRUE) {
		AvalScreenState* _tmp9_ = NULL;
		AvalScreenState* _tmp10_ = NULL;
		_tmp9_ = aval_game_STATE;
		if (!(_tmp9_ != NULL)) {
			break;
		}
		_tmp10_ = aval_game_STATE;
		aval_screen_state_on_enter (_tmp10_);
		aval_game_main_loop ();
	}
	aval_game_quit ();
}


int main (int argc, char ** argv) {
	g_type_init ();
	platform_main_main ();
	return 0;
}


PlatformMain* platform_main_construct (GType object_type) {
	PlatformMain* self = NULL;
	self = (PlatformMain*) aval_game_construct (object_type);
	return self;
}


PlatformMain* platform_main_new (void) {
	return platform_main_construct (PLATFORM_TYPE_MAIN);
}


static void platform_main_class_init (PlatformMainClass * klass) {
	platform_main_parent_class = g_type_class_peek_parent (klass);
	AVAL_GAME_CLASS (klass)->finalize = platform_main_finalize;
}


static void platform_main_instance_init (PlatformMain * self) {
}


static void platform_main_finalize (AvalGame* obj) {
	PlatformMain * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PLATFORM_TYPE_MAIN, PlatformMain);
	AVAL_GAME_CLASS (platform_main_parent_class)->finalize (obj);
}


GType platform_main_get_type (void) {
	static volatile gsize platform_main_type_id__volatile = 0;
	if (g_once_init_enter (&platform_main_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PlatformMainClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) platform_main_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PlatformMain), 0, (GInstanceInitFunc) platform_main_instance_init, NULL };
		GType platform_main_type_id;
		platform_main_type_id = g_type_register_static (AVAL_TYPE_GAME, "PlatformMain", &g_define_type_info, 0);
		g_once_init_leave (&platform_main_type_id__volatile, platform_main_type_id);
	}
	return platform_main_type_id__volatile;
}



