/* player.vala.c generated by valac 0.22.1, the Vala compiler
 * generated from player.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <chipmunk/chipmunk.h>
#include <SDL2/SDL_render.h>
#include <float.h>
#include <math.h>
#include <SDL2/SDL_rect.h>
#include <stdlib.h>
#include <string.h>
#include <SDL2/SDL_image.h>
#include <SDL2/SDL_events.h>
#include <SDL2/SDL.h>
#include <gobject/gvaluecollector.h>


#define PLATFORM_TYPE_PLAYER (platform_player_get_type ())
#define PLATFORM_PLAYER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PLATFORM_TYPE_PLAYER, PlatformPlayer))
#define PLATFORM_PLAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PLATFORM_TYPE_PLAYER, PlatformPlayerClass))
#define PLATFORM_IS_PLAYER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PLATFORM_TYPE_PLAYER))
#define PLATFORM_IS_PLAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PLATFORM_TYPE_PLAYER))
#define PLATFORM_PLAYER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PLATFORM_TYPE_PLAYER, PlatformPlayerClass))

typedef struct _PlatformPlayer PlatformPlayer;
typedef struct _PlatformPlayerClass PlatformPlayerClass;
typedef struct _PlatformPlayerPrivate PlatformPlayerPrivate;

#define AVAL_TYPE_ANIMATION (aval_animation_get_type ())
#define AVAL_ANIMATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AVAL_TYPE_ANIMATION, AvalAnimation))
#define AVAL_ANIMATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AVAL_TYPE_ANIMATION, AvalAnimationClass))
#define AVAL_IS_ANIMATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AVAL_TYPE_ANIMATION))
#define AVAL_IS_ANIMATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AVAL_TYPE_ANIMATION))
#define AVAL_ANIMATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AVAL_TYPE_ANIMATION, AvalAnimationClass))

typedef struct _AvalAnimation AvalAnimation;
typedef struct _AvalAnimationClass AvalAnimationClass;
#define _SDL_DestroyTexture0(var) ((var == NULL) ? NULL : (var = (SDL_DestroyTexture (var), NULL)))
#define _aval_animation_unref0(var) ((var == NULL) ? NULL : (var = (aval_animation_unref (var), NULL)))
#define _cpBodyFree0(var) ((var == NULL) ? NULL : (var = (cpBodyFree (var), NULL)))
#define _cpShapeFree0(var) ((var == NULL) ? NULL : (var = (cpShapeFree (var), NULL)))

#define AVAL_TYPE_ANIMATION_MASK (aval_animation_mask_get_type ())
typedef struct _AvalAnimationMask AvalAnimationMask;
#define _platform_player_unref0(var) ((var == NULL) ? NULL : (var = (platform_player_unref (var), NULL)))
typedef struct _AvalAnimationPrivate AvalAnimationPrivate;
typedef struct _PlatformParamSpecPlayer PlatformParamSpecPlayer;

struct _PlatformPlayer {
	GTypeInstance parent_instance;
	volatile int ref_count;
	PlatformPlayerPrivate * priv;
	gint health;
	cpBody* body;
	cpPolyShape* shape;
};

struct _PlatformPlayerClass {
	GTypeClass parent_class;
	void (*finalize) (PlatformPlayer *self);
};

struct _PlatformPlayerPrivate {
	SDL_Texture* player_texture;
	AvalAnimation* player_animation;
	gdouble player_move_speed;
	gboolean moving[2];
	gboolean attacking;
	gboolean guarding;
	gboolean jumping;
	gboolean inair;
	gboolean crouching;
	gboolean facing_left;
	SDL_Rect view;
};

struct _AvalAnimationMask {
	guint8 y;
	guint8 first_x;
	guint8 last_x;
	gboolean infinite;
};

struct _AvalAnimation {
	GTypeInstance parent_instance;
	volatile int ref_count;
	AvalAnimationPrivate * priv;
	SDL_Point screen_pos;
	gdouble angle;
	SDL_RendererFlip flip;
	gboolean infinite;
	guint16 frame_width;
	guint16 frame_height;
	guint8 actual_x;
	guint8 actual_y;
};

struct _AvalAnimationClass {
	GTypeClass parent_class;
	void (*finalize) (AvalAnimation *self);
};

struct _PlatformParamSpecPlayer {
	GParamSpec parent_instance;
};


static gpointer platform_player_parent_class = NULL;
extern SDL_Renderer* aval_game_WIN_RENDERER;

gpointer platform_player_ref (gpointer instance);
void platform_player_unref (gpointer instance);
GParamSpec* platform_param_spec_player (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void platform_value_set_player (GValue* value, gpointer v_object);
void platform_value_take_player (GValue* value, gpointer v_object);
gpointer platform_value_get_player (const GValue* value);
GType platform_player_get_type (void) G_GNUC_CONST;
gpointer aval_animation_ref (gpointer instance);
void aval_animation_unref (gpointer instance);
GParamSpec* aval_param_spec_animation (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void aval_value_set_animation (GValue* value, gpointer v_object);
void aval_value_take_animation (GValue* value, gpointer v_object);
gpointer aval_value_get_animation (const GValue* value);
GType aval_animation_get_type (void) G_GNUC_CONST;
#define PLATFORM_PLAYER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), PLATFORM_TYPE_PLAYER, PlatformPlayerPrivate))
enum  {
	PLATFORM_PLAYER_DUMMY_PROPERTY
};
#define PLATFORM_PLAYER_PLAYER_IMG "skel.png"
#define PLATFORM_PLAYER_PLAYER_WIDTH 32
#define PLATFORM_PLAYER_PLAYER_HEIGHT 64
GType aval_animation_mask_get_type (void) G_GNUC_CONST;
AvalAnimationMask* aval_animation_mask_dup (const AvalAnimationMask* self);
void aval_animation_mask_free (AvalAnimationMask* self);
#define PLATFORM_PLAYER_MASS ((gdouble) 4)
PlatformPlayer* platform_player_new (SDL_Point start_position, cpSpace* space, SDL_Rect view);
PlatformPlayer* platform_player_construct (GType object_type, SDL_Point start_position, cpSpace* space, SDL_Rect view);
AvalAnimation* aval_animation_new (SDL_Texture* _spritesheet, guint16 _frame_width, guint16 _frame_height, guint8 last_frame_x, guint8 last_frame_y, guint8 start_frame_y, guint8 frame_time, SDL_Point screen_pos, guint8 first_x);
AvalAnimation* aval_animation_construct (GType object_type, SDL_Texture* _spritesheet, guint16 _frame_width, guint16 _frame_height, guint8 last_frame_x, guint8 last_frame_y, guint8 start_frame_y, guint8 frame_time, SDL_Point screen_pos, guint8 first_x);
void aval_animation_set_mask (AvalAnimation* self, AvalAnimationMask* mask);
void platform_player_reset_animation (PlatformPlayer* self, gboolean starting);
void platform_player_touched_ground (cpArbiter* arb, cpSpace* space, void* data);
void platform_player_separated_ground (cpArbiter* arb, cpSpace* space, void* data);
void platform_player_on_event (PlatformPlayer* self, SDL_Event e);
void aval_animation_set_x (AvalAnimation* self, guint8 nvalue);
void platform_player_update (PlatformPlayer* self);
void aval_animation_tick (AvalAnimation* self);
void aval_animation_update_rects (AvalAnimation* self);
void platform_player_draw (PlatformPlayer* self);
void aval_animation_draw (AvalAnimation* self);
void platform_player_dispose (PlatformPlayer* self);
void platform_player_physics_dispose (PlatformPlayer* self, cpSpace* space);
static void platform_player_finalize (PlatformPlayer* obj);

const AvalAnimationMask PLATFORM_PLAYER_AN_IDLE = {(guint8) 0, (guint8) 0, (guint8) 0, FALSE};
const AvalAnimationMask PLATFORM_PLAYER_AN_WALK = {(guint8) 0, (guint8) 1, (guint8) 6, TRUE};
const AvalAnimationMask PLATFORM_PLAYER_AN_CROUCH = {(guint8) 0, (guint8) 7, (guint8) 9, FALSE};
const AvalAnimationMask PLATFORM_PLAYER_AN_STAND = {(guint8) 1, (guint8) 0, (guint8) 0, FALSE};
const AvalAnimationMask PLATFORM_PLAYER_AN_DMG_H = {(guint8) 1, (guint8) 1, (guint8) 2, FALSE};
const AvalAnimationMask PLATFORM_PLAYER_AN_DMG_L = {(guint8) 1, (guint8) 3, (guint8) 4, FALSE};
const AvalAnimationMask PLATFORM_PLAYER_AN_DMG_C = {(guint8) 1, (guint8) 5, (guint8) 6, FALSE};
const AvalAnimationMask PLATFORM_PLAYER_AN_JUMP = {(guint8) 1, (guint8) 7, (guint8) 9, FALSE};
const AvalAnimationMask PLATFORM_PLAYER_AN_VSTRIKE_S = {(guint8) 2, (guint8) 0, (guint8) 6, FALSE};
const AvalAnimationMask PLATFORM_PLAYER_AN_VSTRIKE_C = {(guint8) 3, (guint8) 0, (guint8) 6, FALSE};
const AvalAnimationMask PLATFORM_PLAYER_AN_VSTRIKE_A = {(guint8) 4, (guint8) 4, (guint8) 6, FALSE};
const AvalAnimationMask PLATFORM_PLAYER_AN_HSTRIKE_S = {(guint8) 2, (guint8) 4, (guint8) 6, FALSE};
const AvalAnimationMask PLATFORM_PLAYER_AN_HSTRIKE_C = {(guint8) 3, (guint8) 4, (guint8) 6, FALSE};
const AvalAnimationMask PLATFORM_PLAYER_AN_HSTRIKE_A = {(guint8) 4, (guint8) 4, (guint8) 6, FALSE};
const AvalAnimationMask PLATFORM_PLAYER_AN_PUNCH_S = {(guint8) 2, (guint8) 7, (guint8) 8, TRUE};
const AvalAnimationMask PLATFORM_PLAYER_AN_PUNCH_C = {(guint8) 3, (guint8) 7, (guint8) 8, TRUE};
const AvalAnimationMask PLATFORM_PLAYER_AN_PUNCH_A = {(guint8) 4, (guint8) 7, (guint8) 8, TRUE};
const AvalAnimationMask PLATFORM_PLAYER_AN_GUARD_S = {(guint8) 2, (guint8) 9, (guint8) 9, FALSE};
const AvalAnimationMask PLATFORM_PLAYER_AN_GUARD_C = {(guint8) 3, (guint8) 9, (guint8) 9, FALSE};
const AvalAnimationMask PLATFORM_PLAYER_AN_GUARD_A = {(guint8) 4, (guint8) 9, (guint8) 9, FALSE};

PlatformPlayer* platform_player_construct (GType object_type, SDL_Point start_position, cpSpace* space, SDL_Rect view) {
	PlatformPlayer* self = NULL;
	SDL_Rect _tmp0_ = {0};
	SDL_Renderer* _tmp1_ = NULL;
	SDL_Texture* _tmp2_ = NULL;
	SDL_Texture* _tmp3_ = NULL;
	SDL_Point _tmp4_ = {0};
	AvalAnimation* _tmp5_ = NULL;
	AvalAnimation* _tmp6_ = NULL;
	gboolean _tmp7_[2] = {0};
	cpBody* _tmp8_ = NULL;
	cpSpace* _tmp9_ = NULL;
	cpBody* _tmp10_ = NULL;
	cpBody* _tmp11_ = NULL;
	cpVect _tmp12_ = {0};
	cpVect _tmp13_ = {0};
	cpVect _tmp14_ = {0};
	cpVect _tmp15_ = {0};
	cpVect* _tmp16_ = NULL;
	cpVect* _tmp17_ = NULL;
	gint _tmp17__length1 = 0;
	cpVect _tmp18_ = {0};
	cpPolyShape* _tmp19_ = NULL;
	cpPolyShape* _tmp20_ = NULL;
	cpPolyShape* _tmp21_ = NULL;
	cpSpace* _tmp22_ = NULL;
	cpPolyShape* _tmp23_ = NULL;
	cpSpace* _tmp24_ = NULL;
	cpBody* _tmp25_ = NULL;
	SDL_Point _tmp26_ = {0};
	gint _tmp27_ = 0;
	SDL_Point _tmp28_ = {0};
	gint _tmp29_ = 0;
	cpVect _tmp30_ = {0};
	g_return_val_if_fail (space != NULL, NULL);
	self = (PlatformPlayer*) g_type_create_instance (object_type);
	_tmp0_ = view;
	self->priv->view = _tmp0_;
	_tmp1_ = aval_game_WIN_RENDERER;
	_tmp2_ = IMG_LoadTexture (_tmp1_, PLATFORM_PLAYER_PLAYER_IMG);
	_SDL_DestroyTexture0 (self->priv->player_texture);
	self->priv->player_texture = _tmp2_;
	_tmp3_ = self->priv->player_texture;
	_tmp4_.x = 0;
	_tmp4_.y = 0;
	_tmp5_ = aval_animation_new (_tmp3_, (guint16) PLATFORM_PLAYER_PLAYER_WIDTH, (guint16) PLATFORM_PLAYER_PLAYER_HEIGHT, (guint8) 9, (guint8) 5, (guint8) 0, (guint8) 8, _tmp4_, (guint8) 0);
	_aval_animation_unref0 (self->priv->player_animation);
	self->priv->player_animation = _tmp5_;
	_tmp6_ = self->priv->player_animation;
	aval_animation_set_mask (_tmp6_, &PLATFORM_PLAYER_AN_IDLE);
	self->health = 100;
	self->priv->player_move_speed = (gdouble) 1.6f;
	_tmp7_[0] = FALSE;
	memcpy (self->priv->moving, _tmp7_, 2 * sizeof (gboolean));
	self->priv->attacking = FALSE;
	self->priv->guarding = FALSE;
	self->priv->jumping = FALSE;
	self->priv->facing_left = FALSE;
	self->priv->inair = TRUE;
	platform_player_reset_animation (self, FALSE);
	_tmp8_ = cpBodyNew (PLATFORM_PLAYER_MASS, INFINITY);
	_cpBodyFree0 (self->body);
	self->body = _tmp8_;
	_tmp9_ = space;
	_tmp10_ = self->body;
	cpSpaceAddBody (_tmp9_, _tmp10_);
	_tmp11_ = self->body;
	_tmp12_ = cpv ((gdouble) 0, (gdouble) 0);
	_tmp13_ = cpv ((gdouble) 0, (gdouble) PLATFORM_PLAYER_PLAYER_HEIGHT);
	_tmp14_ = cpv ((gdouble) PLATFORM_PLAYER_PLAYER_WIDTH, (gdouble) PLATFORM_PLAYER_PLAYER_HEIGHT);
	_tmp15_ = cpv ((gdouble) PLATFORM_PLAYER_PLAYER_WIDTH, (gdouble) 0);
	_tmp16_ = g_new0 (cpVect, 4);
	_tmp16_[0] = _tmp12_;
	_tmp16_[1] = _tmp13_;
	_tmp16_[2] = _tmp14_;
	_tmp16_[3] = _tmp15_;
	_tmp17_ = _tmp16_;
	_tmp17__length1 = 4;
	_tmp18_.x = (gdouble) 0;
	_tmp19_ = cpPolyShapeNew (_tmp11_, 4, _tmp17_, _tmp18_);
	_cpShapeFree0 (self->shape);
	self->shape = _tmp19_;
	_tmp17_ = (g_free (_tmp17_), NULL);
	_tmp20_ = self->shape;
	((cpShape*) _tmp20_)->collision_type = (cpCollisionType) 1;
	_tmp21_ = self->shape;
	((cpShape*) _tmp21_)->u = 0.7;
	_tmp22_ = space;
	_tmp23_ = self->shape;
	cpSpaceAddShape (_tmp22_, (cpShape*) _tmp23_);
	_tmp24_ = space;
	cpSpaceAddCollisionHandler (_tmp24_, (cpCollisionType) 0, (cpCollisionType) 1, NULL, NULL, (cpCollisionPostSolveFunc) platform_player_touched_ground, (cpCollisionSeparateFunc) platform_player_separated_ground, self);
	_tmp25_ = self->body;
	_tmp26_ = start_position;
	_tmp27_ = _tmp26_.x;
	_tmp28_ = start_position;
	_tmp29_ = _tmp28_.y;
	_tmp30_.x = (gdouble) (_tmp27_ - (PLATFORM_PLAYER_PLAYER_WIDTH / 2));
	_tmp30_.y = (gdouble) (_tmp29_ - (PLATFORM_PLAYER_PLAYER_WIDTH / 2));
	cpBodySetPos (_tmp25_, _tmp30_);
	return self;
}


PlatformPlayer* platform_player_new (SDL_Point start_position, cpSpace* space, SDL_Rect view) {
	return platform_player_construct (PLATFORM_TYPE_PLAYER, start_position, space, view);
}


static gpointer _platform_player_ref0 (gpointer self) {
	return self ? platform_player_ref (self) : NULL;
}


void platform_player_touched_ground (cpArbiter* arb, cpSpace* space, void* data) {
	PlatformPlayer* player = NULL;
	void* _tmp0_ = NULL;
	PlatformPlayer* _tmp1_ = NULL;
	PlatformPlayer* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	g_return_if_fail (arb != NULL);
	g_return_if_fail (space != NULL);
	_tmp0_ = data;
	_tmp1_ = _platform_player_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, PLATFORM_TYPE_PLAYER, PlatformPlayer));
	player = _tmp1_;
	_tmp2_ = player;
	_tmp3_ = _tmp2_->priv->inair;
	if (_tmp3_) {
		PlatformPlayer* _tmp4_ = NULL;
		PlatformPlayer* _tmp5_ = NULL;
		_tmp4_ = player;
		_tmp4_->priv->inair = FALSE;
		_tmp5_ = player;
		platform_player_reset_animation (_tmp5_, FALSE);
	}
	_platform_player_unref0 (player);
}


void platform_player_separated_ground (cpArbiter* arb, cpSpace* space, void* data) {
	PlatformPlayer* player = NULL;
	void* _tmp0_ = NULL;
	PlatformPlayer* _tmp1_ = NULL;
	PlatformPlayer* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	g_return_if_fail (arb != NULL);
	g_return_if_fail (space != NULL);
	_tmp0_ = data;
	_tmp1_ = _platform_player_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, PLATFORM_TYPE_PLAYER, PlatformPlayer));
	player = _tmp1_;
	_tmp2_ = player;
	_tmp3_ = _tmp2_->priv->inair;
	if (!_tmp3_) {
		PlatformPlayer* _tmp4_ = NULL;
		PlatformPlayer* _tmp5_ = NULL;
		PlatformPlayer* _tmp6_ = NULL;
		gboolean _tmp7_ = FALSE;
		_tmp4_ = player;
		_tmp4_->priv->inair = TRUE;
		_tmp5_ = player;
		_tmp6_ = player;
		_tmp7_ = _tmp6_->priv->jumping;
		platform_player_reset_animation (_tmp5_, _tmp7_);
	}
	_platform_player_unref0 (player);
}


void platform_player_on_event (PlatformPlayer* self, SDL_Event e) {
	SDL_Event _tmp0_ = {0};
	SDL_EventType _tmp1_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = e;
	_tmp1_ = _tmp0_.type;
	if (_tmp1_ == SDL_KEYDOWN) {
		gboolean _tmp2_ = FALSE;
		SDL_Event _tmp3_ = {0};
		SDL_KeyboardEvent _tmp4_ = {0};
		SDL_Keysym _tmp5_ = {0};
		SDL_Keycode _tmp6_ = 0;
		gboolean _tmp11_ = FALSE;
		_tmp3_ = e;
		_tmp4_ = _tmp3_.key;
		_tmp5_ = _tmp4_.keysym;
		_tmp6_ = _tmp5_.sym;
		if (_tmp6_ == SDLK_LEFT) {
			_tmp2_ = TRUE;
		} else {
			SDL_Event _tmp7_ = {0};
			SDL_KeyboardEvent _tmp8_ = {0};
			SDL_Keysym _tmp9_ = {0};
			SDL_Keycode _tmp10_ = 0;
			_tmp7_ = e;
			_tmp8_ = _tmp7_.key;
			_tmp9_ = _tmp8_.keysym;
			_tmp10_ = _tmp9_.sym;
			_tmp2_ = _tmp10_ == SDLK_a;
		}
		_tmp11_ = _tmp2_;
		if (_tmp11_) {
			gboolean _tmp12_ = FALSE;
			self->priv->facing_left = TRUE;
			_tmp12_ = self->priv->moving[0];
			if (!_tmp12_) {
				gboolean _tmp13_ = FALSE;
				self->priv->moving[0] = TRUE;
				_tmp13_ = self->priv->moving[0];
				platform_player_reset_animation (self, FALSE);
			}
		} else {
			gboolean _tmp14_ = FALSE;
			SDL_Event _tmp15_ = {0};
			SDL_KeyboardEvent _tmp16_ = {0};
			SDL_Keysym _tmp17_ = {0};
			SDL_Keycode _tmp18_ = 0;
			gboolean _tmp23_ = FALSE;
			_tmp15_ = e;
			_tmp16_ = _tmp15_.key;
			_tmp17_ = _tmp16_.keysym;
			_tmp18_ = _tmp17_.sym;
			if (_tmp18_ == SDLK_RIGHT) {
				_tmp14_ = TRUE;
			} else {
				SDL_Event _tmp19_ = {0};
				SDL_KeyboardEvent _tmp20_ = {0};
				SDL_Keysym _tmp21_ = {0};
				SDL_Keycode _tmp22_ = 0;
				_tmp19_ = e;
				_tmp20_ = _tmp19_.key;
				_tmp21_ = _tmp20_.keysym;
				_tmp22_ = _tmp21_.sym;
				_tmp14_ = _tmp22_ == SDLK_d;
			}
			_tmp23_ = _tmp14_;
			if (_tmp23_) {
				gboolean _tmp24_ = FALSE;
				self->priv->facing_left = FALSE;
				_tmp24_ = self->priv->moving[1];
				if (!_tmp24_) {
					gboolean _tmp25_ = FALSE;
					self->priv->moving[1] = TRUE;
					_tmp25_ = self->priv->moving[1];
					platform_player_reset_animation (self, FALSE);
				}
			} else {
				gboolean _tmp26_ = FALSE;
				SDL_Event _tmp27_ = {0};
				SDL_KeyboardEvent _tmp28_ = {0};
				SDL_Keysym _tmp29_ = {0};
				SDL_Keycode _tmp30_ = 0;
				gboolean _tmp35_ = FALSE;
				_tmp27_ = e;
				_tmp28_ = _tmp27_.key;
				_tmp29_ = _tmp28_.keysym;
				_tmp30_ = _tmp29_.sym;
				if (_tmp30_ == SDLK_DOWN) {
					_tmp26_ = TRUE;
				} else {
					SDL_Event _tmp31_ = {0};
					SDL_KeyboardEvent _tmp32_ = {0};
					SDL_Keysym _tmp33_ = {0};
					SDL_Keycode _tmp34_ = 0;
					_tmp31_ = e;
					_tmp32_ = _tmp31_.key;
					_tmp33_ = _tmp32_.keysym;
					_tmp34_ = _tmp33_.sym;
					_tmp26_ = _tmp34_ == SDLK_s;
				}
				_tmp35_ = _tmp26_;
				if (_tmp35_) {
					gboolean _tmp36_ = FALSE;
					_tmp36_ = self->priv->crouching;
					if (!_tmp36_) {
						self->priv->crouching = TRUE;
						platform_player_reset_animation (self, TRUE);
					}
				} else {
					gboolean _tmp37_ = FALSE;
					SDL_Event _tmp38_ = {0};
					SDL_KeyboardEvent _tmp39_ = {0};
					SDL_Keysym _tmp40_ = {0};
					SDL_Keycode _tmp41_ = 0;
					gboolean _tmp46_ = FALSE;
					_tmp38_ = e;
					_tmp39_ = _tmp38_.key;
					_tmp40_ = _tmp39_.keysym;
					_tmp41_ = _tmp40_.sym;
					if (_tmp41_ == SDLK_LSHIFT) {
						_tmp37_ = TRUE;
					} else {
						SDL_Event _tmp42_ = {0};
						SDL_KeyboardEvent _tmp43_ = {0};
						SDL_Keysym _tmp44_ = {0};
						SDL_Keycode _tmp45_ = 0;
						_tmp42_ = e;
						_tmp43_ = _tmp42_.key;
						_tmp44_ = _tmp43_.keysym;
						_tmp45_ = _tmp44_.sym;
						_tmp37_ = _tmp45_ == SDLK_KP_4;
					}
					_tmp46_ = _tmp37_;
					if (_tmp46_) {
						gboolean _tmp47_ = FALSE;
						_tmp47_ = self->priv->attacking;
						if (!_tmp47_) {
							self->priv->attacking = TRUE;
							platform_player_reset_animation (self, FALSE);
						}
					} else {
						gboolean _tmp48_ = FALSE;
						SDL_Event _tmp49_ = {0};
						SDL_KeyboardEvent _tmp50_ = {0};
						SDL_Keysym _tmp51_ = {0};
						SDL_Keycode _tmp52_ = 0;
						gboolean _tmp57_ = FALSE;
						_tmp49_ = e;
						_tmp50_ = _tmp49_.key;
						_tmp51_ = _tmp50_.keysym;
						_tmp52_ = _tmp51_.sym;
						if (_tmp52_ == SDLK_LCTRL) {
							_tmp48_ = TRUE;
						} else {
							SDL_Event _tmp53_ = {0};
							SDL_KeyboardEvent _tmp54_ = {0};
							SDL_Keysym _tmp55_ = {0};
							SDL_Keycode _tmp56_ = 0;
							_tmp53_ = e;
							_tmp54_ = _tmp53_.key;
							_tmp55_ = _tmp54_.keysym;
							_tmp56_ = _tmp55_.sym;
							_tmp48_ = _tmp56_ == SDLK_KP_6;
						}
						_tmp57_ = _tmp48_;
						if (_tmp57_) {
							gboolean _tmp58_ = FALSE;
							_tmp58_ = self->priv->guarding;
							if (!_tmp58_) {
								self->priv->guarding = TRUE;
								platform_player_reset_animation (self, FALSE);
							}
						} else {
							gboolean _tmp59_ = FALSE;
							SDL_Event _tmp60_ = {0};
							SDL_KeyboardEvent _tmp61_ = {0};
							SDL_Keysym _tmp62_ = {0};
							SDL_Keycode _tmp63_ = 0;
							gboolean _tmp68_ = FALSE;
							_tmp60_ = e;
							_tmp61_ = _tmp60_.key;
							_tmp62_ = _tmp61_.keysym;
							_tmp63_ = _tmp62_.sym;
							if (_tmp63_ == SDLK_SPACE) {
								_tmp59_ = TRUE;
							} else {
								SDL_Event _tmp64_ = {0};
								SDL_KeyboardEvent _tmp65_ = {0};
								SDL_Keysym _tmp66_ = {0};
								SDL_Keycode _tmp67_ = 0;
								_tmp64_ = e;
								_tmp65_ = _tmp64_.key;
								_tmp66_ = _tmp65_.keysym;
								_tmp67_ = _tmp66_.sym;
								_tmp59_ = _tmp67_ == SDLK_KP_5;
							}
							_tmp68_ = _tmp59_;
							if (_tmp68_) {
								gboolean _tmp69_ = FALSE;
								gboolean _tmp73_ = FALSE;
								_tmp69_ = self->priv->inair;
								if (!_tmp69_) {
									cpBody* _tmp70_ = NULL;
									cpVect _tmp71_ = {0};
									cpVect _tmp72_ = {0};
									_tmp70_ = self->body;
									_tmp71_.x = (gdouble) 0;
									_tmp71_.y = (gdouble) (-20);
									_tmp72_.x = (gdouble) 0;
									cpBodyApplyImpulse (_tmp70_, _tmp71_, _tmp72_);
								}
								_tmp73_ = self->priv->jumping;
								if (!_tmp73_) {
									self->priv->jumping = TRUE;
								}
							}
						}
					}
				}
			}
		}
	} else {
		SDL_Event _tmp74_ = {0};
		SDL_EventType _tmp75_ = 0;
		_tmp74_ = e;
		_tmp75_ = _tmp74_.type;
		if (_tmp75_ == SDL_KEYUP) {
			gboolean _tmp76_ = FALSE;
			SDL_Event _tmp77_ = {0};
			SDL_KeyboardEvent _tmp78_ = {0};
			SDL_Keysym _tmp79_ = {0};
			SDL_Keycode _tmp80_ = 0;
			gboolean _tmp85_ = FALSE;
			_tmp77_ = e;
			_tmp78_ = _tmp77_.key;
			_tmp79_ = _tmp78_.keysym;
			_tmp80_ = _tmp79_.sym;
			if (_tmp80_ == SDLK_LEFT) {
				_tmp76_ = TRUE;
			} else {
				SDL_Event _tmp81_ = {0};
				SDL_KeyboardEvent _tmp82_ = {0};
				SDL_Keysym _tmp83_ = {0};
				SDL_Keycode _tmp84_ = 0;
				_tmp81_ = e;
				_tmp82_ = _tmp81_.key;
				_tmp83_ = _tmp82_.keysym;
				_tmp84_ = _tmp83_.sym;
				_tmp76_ = _tmp84_ == SDLK_a;
			}
			_tmp85_ = _tmp76_;
			if (_tmp85_) {
				gboolean _tmp86_ = FALSE;
				_tmp86_ = self->priv->moving[0];
				if (_tmp86_) {
					gboolean _tmp87_ = FALSE;
					gboolean _tmp88_ = FALSE;
					_tmp87_ = self->priv->moving[1];
					if (_tmp87_) {
						self->priv->facing_left = FALSE;
					}
					self->priv->moving[0] = FALSE;
					_tmp88_ = self->priv->moving[0];
					platform_player_reset_animation (self, FALSE);
				}
			} else {
				gboolean _tmp89_ = FALSE;
				SDL_Event _tmp90_ = {0};
				SDL_KeyboardEvent _tmp91_ = {0};
				SDL_Keysym _tmp92_ = {0};
				SDL_Keycode _tmp93_ = 0;
				gboolean _tmp98_ = FALSE;
				_tmp90_ = e;
				_tmp91_ = _tmp90_.key;
				_tmp92_ = _tmp91_.keysym;
				_tmp93_ = _tmp92_.sym;
				if (_tmp93_ == SDLK_RIGHT) {
					_tmp89_ = TRUE;
				} else {
					SDL_Event _tmp94_ = {0};
					SDL_KeyboardEvent _tmp95_ = {0};
					SDL_Keysym _tmp96_ = {0};
					SDL_Keycode _tmp97_ = 0;
					_tmp94_ = e;
					_tmp95_ = _tmp94_.key;
					_tmp96_ = _tmp95_.keysym;
					_tmp97_ = _tmp96_.sym;
					_tmp89_ = _tmp97_ == SDLK_d;
				}
				_tmp98_ = _tmp89_;
				if (_tmp98_) {
					gboolean _tmp99_ = FALSE;
					_tmp99_ = self->priv->moving[1];
					if (_tmp99_) {
						gboolean _tmp100_ = FALSE;
						gboolean _tmp101_ = FALSE;
						_tmp100_ = self->priv->moving[0];
						if (_tmp100_) {
							self->priv->facing_left = TRUE;
						}
						self->priv->moving[1] = FALSE;
						_tmp101_ = self->priv->moving[1];
						platform_player_reset_animation (self, FALSE);
					}
				} else {
					gboolean _tmp102_ = FALSE;
					SDL_Event _tmp103_ = {0};
					SDL_KeyboardEvent _tmp104_ = {0};
					SDL_Keysym _tmp105_ = {0};
					SDL_Keycode _tmp106_ = 0;
					gboolean _tmp111_ = FALSE;
					_tmp103_ = e;
					_tmp104_ = _tmp103_.key;
					_tmp105_ = _tmp104_.keysym;
					_tmp106_ = _tmp105_.sym;
					if (_tmp106_ == SDLK_DOWN) {
						_tmp102_ = TRUE;
					} else {
						SDL_Event _tmp107_ = {0};
						SDL_KeyboardEvent _tmp108_ = {0};
						SDL_Keysym _tmp109_ = {0};
						SDL_Keycode _tmp110_ = 0;
						_tmp107_ = e;
						_tmp108_ = _tmp107_.key;
						_tmp109_ = _tmp108_.keysym;
						_tmp110_ = _tmp109_.sym;
						_tmp102_ = _tmp110_ == SDLK_s;
					}
					_tmp111_ = _tmp102_;
					if (_tmp111_) {
						gboolean _tmp112_ = FALSE;
						_tmp112_ = self->priv->crouching;
						if (_tmp112_) {
							self->priv->crouching = FALSE;
							platform_player_reset_animation (self, FALSE);
						}
					} else {
						gboolean _tmp113_ = FALSE;
						SDL_Event _tmp114_ = {0};
						SDL_KeyboardEvent _tmp115_ = {0};
						SDL_Keysym _tmp116_ = {0};
						SDL_Keycode _tmp117_ = 0;
						gboolean _tmp122_ = FALSE;
						_tmp114_ = e;
						_tmp115_ = _tmp114_.key;
						_tmp116_ = _tmp115_.keysym;
						_tmp117_ = _tmp116_.sym;
						if (_tmp117_ == SDLK_LSHIFT) {
							_tmp113_ = TRUE;
						} else {
							SDL_Event _tmp118_ = {0};
							SDL_KeyboardEvent _tmp119_ = {0};
							SDL_Keysym _tmp120_ = {0};
							SDL_Keycode _tmp121_ = 0;
							_tmp118_ = e;
							_tmp119_ = _tmp118_.key;
							_tmp120_ = _tmp119_.keysym;
							_tmp121_ = _tmp120_.sym;
							_tmp113_ = _tmp121_ == SDLK_KP_4;
						}
						_tmp122_ = _tmp113_;
						if (_tmp122_) {
							gboolean _tmp123_ = FALSE;
							_tmp123_ = self->priv->attacking;
							if (_tmp123_) {
								self->priv->attacking = FALSE;
								platform_player_reset_animation (self, FALSE);
							}
						} else {
							gboolean _tmp124_ = FALSE;
							SDL_Event _tmp125_ = {0};
							SDL_KeyboardEvent _tmp126_ = {0};
							SDL_Keysym _tmp127_ = {0};
							SDL_Keycode _tmp128_ = 0;
							gboolean _tmp133_ = FALSE;
							_tmp125_ = e;
							_tmp126_ = _tmp125_.key;
							_tmp127_ = _tmp126_.keysym;
							_tmp128_ = _tmp127_.sym;
							if (_tmp128_ == SDLK_LCTRL) {
								_tmp124_ = TRUE;
							} else {
								SDL_Event _tmp129_ = {0};
								SDL_KeyboardEvent _tmp130_ = {0};
								SDL_Keysym _tmp131_ = {0};
								SDL_Keycode _tmp132_ = 0;
								_tmp129_ = e;
								_tmp130_ = _tmp129_.key;
								_tmp131_ = _tmp130_.keysym;
								_tmp132_ = _tmp131_.sym;
								_tmp124_ = _tmp132_ == SDLK_KP_6;
							}
							_tmp133_ = _tmp124_;
							if (_tmp133_) {
								gboolean _tmp134_ = FALSE;
								_tmp134_ = self->priv->guarding;
								if (_tmp134_) {
									self->priv->guarding = FALSE;
									platform_player_reset_animation (self, FALSE);
								}
							} else {
								gboolean _tmp135_ = FALSE;
								SDL_Event _tmp136_ = {0};
								SDL_KeyboardEvent _tmp137_ = {0};
								SDL_Keysym _tmp138_ = {0};
								SDL_Keycode _tmp139_ = 0;
								gboolean _tmp144_ = FALSE;
								_tmp136_ = e;
								_tmp137_ = _tmp136_.key;
								_tmp138_ = _tmp137_.keysym;
								_tmp139_ = _tmp138_.sym;
								if (_tmp139_ == SDLK_SPACE) {
									_tmp135_ = TRUE;
								} else {
									SDL_Event _tmp140_ = {0};
									SDL_KeyboardEvent _tmp141_ = {0};
									SDL_Keysym _tmp142_ = {0};
									SDL_Keycode _tmp143_ = 0;
									_tmp140_ = e;
									_tmp141_ = _tmp140_.key;
									_tmp142_ = _tmp141_.keysym;
									_tmp143_ = _tmp142_.sym;
									_tmp135_ = _tmp143_ == SDLK_KP_5;
								}
								_tmp144_ = _tmp135_;
								if (_tmp144_) {
									gboolean _tmp145_ = FALSE;
									_tmp145_ = self->priv->jumping;
									if (_tmp145_) {
										self->priv->jumping = FALSE;
									}
								}
							}
						}
					}
				}
			}
		}
	}
}


void platform_player_reset_animation (PlatformPlayer* self, gboolean starting) {
	SDL_RendererFlip _tmp0_ = 0;
	gboolean _tmp1_ = FALSE;
	AvalAnimation* _tmp2_ = NULL;
	SDL_RendererFlip _tmp3_ = 0;
	gboolean _tmp4_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp1_ = self->priv->facing_left;
	if (_tmp1_) {
		_tmp0_ = SDL_FLIP_HORIZONTAL;
	} else {
		_tmp0_ = SDL_FLIP_NONE;
	}
	_tmp2_ = self->priv->player_animation;
	_tmp3_ = _tmp0_;
	_tmp2_->flip = _tmp3_;
	_tmp4_ = self->priv->inair;
	if (_tmp4_) {
		gboolean _tmp5_ = FALSE;
		_tmp5_ = self->priv->attacking;
		if (_tmp5_) {
			AvalAnimation* _tmp6_ = NULL;
			_tmp6_ = self->priv->player_animation;
			aval_animation_set_mask (_tmp6_, &PLATFORM_PLAYER_AN_PUNCH_A);
		} else {
			gboolean _tmp7_ = FALSE;
			_tmp7_ = self->priv->guarding;
			if (_tmp7_) {
				AvalAnimation* _tmp8_ = NULL;
				_tmp8_ = self->priv->player_animation;
				aval_animation_set_mask (_tmp8_, &PLATFORM_PLAYER_AN_GUARD_A);
			} else {
				AvalAnimation* _tmp9_ = NULL;
				gboolean _tmp10_ = FALSE;
				_tmp9_ = self->priv->player_animation;
				aval_animation_set_mask (_tmp9_, &PLATFORM_PLAYER_AN_JUMP);
				_tmp10_ = starting;
				if (!_tmp10_) {
					AvalAnimation* _tmp11_ = NULL;
					_tmp11_ = self->priv->player_animation;
					aval_animation_set_x (_tmp11_, (guint8) 99);
				}
			}
		}
	} else {
		gboolean _tmp12_ = FALSE;
		_tmp12_ = self->priv->crouching;
		if (_tmp12_) {
			gboolean _tmp13_ = FALSE;
			_tmp13_ = self->priv->attacking;
			if (_tmp13_) {
				AvalAnimation* _tmp14_ = NULL;
				_tmp14_ = self->priv->player_animation;
				aval_animation_set_mask (_tmp14_, &PLATFORM_PLAYER_AN_PUNCH_C);
			} else {
				gboolean _tmp15_ = FALSE;
				_tmp15_ = self->priv->guarding;
				if (_tmp15_) {
					AvalAnimation* _tmp16_ = NULL;
					_tmp16_ = self->priv->player_animation;
					aval_animation_set_mask (_tmp16_, &PLATFORM_PLAYER_AN_GUARD_C);
				} else {
					AvalAnimation* _tmp17_ = NULL;
					gboolean _tmp18_ = FALSE;
					_tmp17_ = self->priv->player_animation;
					aval_animation_set_mask (_tmp17_, &PLATFORM_PLAYER_AN_CROUCH);
					_tmp18_ = starting;
					if (!_tmp18_) {
						AvalAnimation* _tmp19_ = NULL;
						_tmp19_ = self->priv->player_animation;
						aval_animation_set_x (_tmp19_, (guint8) 99);
					}
				}
			}
		} else {
			gboolean _tmp20_ = FALSE;
			_tmp20_ = self->priv->attacking;
			if (_tmp20_) {
				AvalAnimation* _tmp21_ = NULL;
				_tmp21_ = self->priv->player_animation;
				aval_animation_set_mask (_tmp21_, &PLATFORM_PLAYER_AN_PUNCH_S);
			} else {
				gboolean _tmp22_ = FALSE;
				_tmp22_ = self->priv->guarding;
				if (_tmp22_) {
					AvalAnimation* _tmp23_ = NULL;
					_tmp23_ = self->priv->player_animation;
					aval_animation_set_mask (_tmp23_, &PLATFORM_PLAYER_AN_GUARD_S);
				} else {
					gboolean _tmp24_ = FALSE;
					gboolean _tmp25_ = FALSE;
					gboolean _tmp26_ = FALSE;
					gboolean _tmp28_ = FALSE;
					gboolean _tmp33_ = FALSE;
					_tmp26_ = self->priv->moving[0];
					if (_tmp26_) {
						_tmp25_ = TRUE;
					} else {
						gboolean _tmp27_ = FALSE;
						_tmp27_ = self->priv->moving[1];
						_tmp25_ = _tmp27_;
					}
					_tmp28_ = _tmp25_;
					if (_tmp28_) {
						gboolean _tmp29_ = FALSE;
						gboolean _tmp30_ = FALSE;
						gboolean _tmp32_ = FALSE;
						_tmp30_ = self->priv->moving[0];
						if (_tmp30_) {
							gboolean _tmp31_ = FALSE;
							_tmp31_ = self->priv->moving[1];
							_tmp29_ = _tmp31_;
						} else {
							_tmp29_ = FALSE;
						}
						_tmp32_ = _tmp29_;
						_tmp24_ = !_tmp32_;
					} else {
						_tmp24_ = FALSE;
					}
					_tmp33_ = _tmp24_;
					if (_tmp33_) {
						AvalAnimation* _tmp34_ = NULL;
						_tmp34_ = self->priv->player_animation;
						aval_animation_set_mask (_tmp34_, &PLATFORM_PLAYER_AN_WALK);
					} else {
						AvalAnimation* _tmp35_ = NULL;
						_tmp35_ = self->priv->player_animation;
						aval_animation_set_mask (_tmp35_, &PLATFORM_PLAYER_AN_IDLE);
					}
				}
			}
		}
	}
}


void platform_player_update (PlatformPlayer* self) {
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	gboolean _tmp5_ = FALSE;
	gboolean _tmp10_ = FALSE;
	gboolean _tmp21_ = FALSE;
	AvalAnimation* _tmp29_ = NULL;
	cpBody* _tmp30_ = NULL;
	cpVect _tmp31_ = {0};
	gdouble _tmp32_ = 0.0;
	SDL_Rect _tmp33_ = {0};
	gint _tmp34_ = 0;
	cpBody* _tmp35_ = NULL;
	cpVect _tmp36_ = {0};
	gdouble _tmp37_ = 0.0;
	SDL_Rect _tmp38_ = {0};
	gint _tmp39_ = 0;
	SDL_Point _tmp40_ = {0};
	AvalAnimation* _tmp41_ = NULL;
	AvalAnimation* _tmp42_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp3_ = self->priv->moving[0];
	if (!_tmp3_) {
		gboolean _tmp4_ = FALSE;
		_tmp4_ = self->priv->moving[1];
		_tmp2_ = !_tmp4_;
	} else {
		_tmp2_ = FALSE;
	}
	_tmp5_ = _tmp2_;
	if (_tmp5_) {
		_tmp1_ = TRUE;
	} else {
		gboolean _tmp6_ = FALSE;
		gboolean _tmp7_ = FALSE;
		gboolean _tmp9_ = FALSE;
		_tmp7_ = self->priv->moving[0];
		if (_tmp7_) {
			gboolean _tmp8_ = FALSE;
			_tmp8_ = self->priv->moving[1];
			_tmp6_ = _tmp8_;
		} else {
			_tmp6_ = FALSE;
		}
		_tmp9_ = _tmp6_;
		_tmp1_ = _tmp9_;
	}
	_tmp10_ = _tmp1_;
	if (_tmp10_) {
		_tmp0_ = TRUE;
	} else {
		gboolean _tmp11_ = FALSE;
		gboolean _tmp12_ = FALSE;
		gboolean _tmp20_ = FALSE;
		_tmp12_ = self->priv->inair;
		if (!_tmp12_) {
			gboolean _tmp13_ = FALSE;
			gboolean _tmp14_ = FALSE;
			gboolean _tmp15_ = FALSE;
			gboolean _tmp17_ = FALSE;
			gboolean _tmp19_ = FALSE;
			_tmp15_ = self->priv->guarding;
			if (_tmp15_) {
				_tmp14_ = TRUE;
			} else {
				gboolean _tmp16_ = FALSE;
				_tmp16_ = self->priv->attacking;
				_tmp14_ = _tmp16_;
			}
			_tmp17_ = _tmp14_;
			if (_tmp17_) {
				_tmp13_ = TRUE;
			} else {
				gboolean _tmp18_ = FALSE;
				_tmp18_ = self->priv->crouching;
				_tmp13_ = _tmp18_;
			}
			_tmp19_ = _tmp13_;
			_tmp11_ = _tmp19_;
		} else {
			_tmp11_ = FALSE;
		}
		_tmp20_ = _tmp11_;
		_tmp0_ = _tmp20_;
	}
	_tmp21_ = _tmp0_;
	if (_tmp21_) {
		cpBody* _tmp22_ = NULL;
		_tmp22_ = self->body;
		_tmp22_->v.x = (gdouble) 0;
	} else {
		gboolean _tmp23_ = FALSE;
		_tmp23_ = self->priv->moving[0];
		if (_tmp23_) {
			cpBody* _tmp24_ = NULL;
			gdouble _tmp25_ = 0.0;
			_tmp24_ = self->body;
			_tmp25_ = self->priv->player_move_speed;
			_tmp24_->v.x = -_tmp25_;
		} else {
			gboolean _tmp26_ = FALSE;
			_tmp26_ = self->priv->moving[1];
			if (_tmp26_) {
				cpBody* _tmp27_ = NULL;
				gdouble _tmp28_ = 0.0;
				_tmp27_ = self->body;
				_tmp28_ = self->priv->player_move_speed;
				_tmp27_->v.x = _tmp28_;
			}
		}
	}
	_tmp29_ = self->priv->player_animation;
	_tmp30_ = self->body;
	_tmp31_ = _tmp30_->p;
	_tmp32_ = _tmp31_.x;
	_tmp33_ = self->priv->view;
	_tmp34_ = _tmp33_.x;
	_tmp35_ = self->body;
	_tmp36_ = _tmp35_->p;
	_tmp37_ = _tmp36_.y;
	_tmp38_ = self->priv->view;
	_tmp39_ = _tmp38_.y;
	_tmp40_.x = ((gint) _tmp32_) - _tmp34_;
	_tmp40_.y = ((gint) _tmp37_) - _tmp39_;
	_tmp29_->screen_pos = _tmp40_;
	_tmp41_ = self->priv->player_animation;
	aval_animation_tick (_tmp41_);
	_tmp42_ = self->priv->player_animation;
	aval_animation_update_rects (_tmp42_);
}


void platform_player_draw (PlatformPlayer* self) {
	AvalAnimation* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->player_animation;
	aval_animation_draw (_tmp0_);
}


void platform_player_dispose (PlatformPlayer* self) {
	g_return_if_fail (self != NULL);
	_SDL_DestroyTexture0 (self->priv->player_texture);
	self->priv->player_texture = NULL;
	_aval_animation_unref0 (self->priv->player_animation);
	self->priv->player_animation = NULL;
}


void platform_player_physics_dispose (PlatformPlayer* self, cpSpace* space) {
	cpSpace* _tmp0_ = NULL;
	cpBody* _tmp1_ = NULL;
	cpSpace* _tmp2_ = NULL;
	cpPolyShape* _tmp3_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (space != NULL);
	_tmp0_ = space;
	_tmp1_ = self->body;
	cpSpaceRemoveBody (_tmp0_, _tmp1_);
	_tmp2_ = space;
	_tmp3_ = self->shape;
	cpSpaceRemoveShape (_tmp2_, (cpShape*) _tmp3_);
	_cpBodyFree0 (self->body);
	self->body = NULL;
	_cpShapeFree0 (self->shape);
	self->shape = NULL;
}


static void platform_value_player_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void platform_value_player_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		platform_player_unref (value->data[0].v_pointer);
	}
}


static void platform_value_player_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = platform_player_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer platform_value_player_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* platform_value_player_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		PlatformPlayer* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = platform_player_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* platform_value_player_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	PlatformPlayer** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = platform_player_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* platform_param_spec_player (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	PlatformParamSpecPlayer* spec;
	g_return_val_if_fail (g_type_is_a (object_type, PLATFORM_TYPE_PLAYER), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer platform_value_get_player (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, PLATFORM_TYPE_PLAYER), NULL);
	return value->data[0].v_pointer;
}


void platform_value_set_player (GValue* value, gpointer v_object) {
	PlatformPlayer* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, PLATFORM_TYPE_PLAYER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, PLATFORM_TYPE_PLAYER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		platform_player_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		platform_player_unref (old);
	}
}


void platform_value_take_player (GValue* value, gpointer v_object) {
	PlatformPlayer* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, PLATFORM_TYPE_PLAYER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, PLATFORM_TYPE_PLAYER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		platform_player_unref (old);
	}
}


static void platform_player_class_init (PlatformPlayerClass * klass) {
	platform_player_parent_class = g_type_class_peek_parent (klass);
	PLATFORM_PLAYER_CLASS (klass)->finalize = platform_player_finalize;
	g_type_class_add_private (klass, sizeof (PlatformPlayerPrivate));
}


static void platform_player_instance_init (PlatformPlayer * self) {
	self->priv = PLATFORM_PLAYER_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void platform_player_finalize (PlatformPlayer* obj) {
	PlatformPlayer * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, PLATFORM_TYPE_PLAYER, PlatformPlayer);
	_SDL_DestroyTexture0 (self->priv->player_texture);
	_aval_animation_unref0 (self->priv->player_animation);
	_cpBodyFree0 (self->body);
	_cpShapeFree0 (self->shape);
}


GType platform_player_get_type (void) {
	static volatile gsize platform_player_type_id__volatile = 0;
	if (g_once_init_enter (&platform_player_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { platform_value_player_init, platform_value_player_free_value, platform_value_player_copy_value, platform_value_player_peek_pointer, "p", platform_value_player_collect_value, "p", platform_value_player_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (PlatformPlayerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) platform_player_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PlatformPlayer), 0, (GInstanceInitFunc) platform_player_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType platform_player_type_id;
		platform_player_type_id = g_type_register_fundamental (g_type_fundamental_next (), "PlatformPlayer", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&platform_player_type_id__volatile, platform_player_type_id);
	}
	return platform_player_type_id__volatile;
}


gpointer platform_player_ref (gpointer instance) {
	PlatformPlayer* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void platform_player_unref (gpointer instance) {
	PlatformPlayer* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		PLATFORM_PLAYER_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



