#!/usr/bin/env ruby
# encoding: utf-8
#----------------------------------------------------------------------------------------------------------------------
# The MIT License (MIT)
#
# Copyright (c) 2013 Christian Ferraz Lemos de Sousa
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
# documentation files (the "Software"), to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
# Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
# WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS
# OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#----------------------------------------------------------------------------------------------------------------------

require_relative 'vm'
include Avalanche

task(:default) do 
  # creating the bytecode
  bc = Bytecode.new

  # setting integers
  bc << Bytecode.new(Type::OpInt, 0, Int::Equal, 4)
  bc << Bytecode.new(Type::OpInt, 0, Int::AnyRoot, 2)
  bc << Bytecode.new(Type::ConOutDynamic, 0, 0)

  # if int[0] == 10
  #bc << Bytecode.new(Type::IfInteger, 0, 10)
  #bc.last << Bytecode.new(Type::ConoutInteger, 1)

  # print int[0]
  #bc << Bytecode.new(Type::ConoutInteger, 0)

  # running the virtual machine
  vm = VirtualMachine.new bc
  vm.run true
end
